// Code generated by @apexlang/codegen. DO NOT EDIT.

package jot

import (
	"github.com/nanobus/iota/go/wasmrs/invoke"
)

var (
	gCaller invoke.Caller
)

func Initialize(caller invoke.Caller) {
	gCaller = caller
}
