TARGET := "wasm32-wasi"
NAME := "sample"

build:
	apex generate
	@mkdir -p build
	cargo build --target={{TARGET}} --target-dir=./target --release
	wasmrs-ops ./target/{{TARGET}}/release/{{NAME}}.wasm
	mkdir -p build
	cp ./target/{{TARGET}}/release/{{NAME}}.wasm ./build/{{NAME}}.wasm
