FROM nanobus/nanobus:v0.0.6

COPY ./bus.yaml /app/bus.yaml
COPY ./web/static /app/static
COPY ./ui /app/ui
COPY ./iotas/jot/apex.aidl /app/iotas/jot/apex.aidl
COPY ./iotas/jot/bus.yaml /app/iotas/jot/bus.yaml
COPY ./iotas/jot/build /app/iotas/jot/build
COPY ./iotas/follow /app/iotas/follow
COPY ./iotas/like /app/iotas/like
COPY ./iotas/message /app/iotas/message
COPY ./iotas/user /app/iotas/user