
build_dir:="build"

build TARGET="wasm32-unknown-unknown" PROFILE="release": codegen
  cargo build {{ if PROFILE == "release" {"--release"} else {""} }} --target={{TARGET}}
  mkdir -p {{build_dir}}
  cp ./target/{{TARGET}}/{{PROFILE}}/*.wasm {{build_dir}}/
  for file in `ls {{build_dir}}`; do wasmrs-ops {{build_dir}}/$file; done

debug:
  just build "wasm32-wasi" "debug"

codegen:
  apex generate
