// Code generated by @apexlang/codegen. DO NOT EDIT.

package sample

import (
	"context"

	"github.com/nanobus/iota/go/rx/mono"
)

type ns struct{}

func (n *ns) Namespace() string {
	return "suite"
}

// Test interface
type Test interface {
	// Returns 'test'
	Op(ctx context.Context) mono.Mono[string]
	// Returns the input string reversed
	Reverse(ctx context.Context, input string) mono.Mono[string]
}

type External interface {
	// Uppercases a string
	Uppercase(ctx context.Context, input string) mono.Mono[string]
}
