// Code generated by @apexlang/codegen. DO NOT EDIT.

package user

import (
	"context"

	"github.com/google/uuid"
	"github.com/nanobus/iota/go/wasmrs/rx/flux"
	"github.com/nanobus/iota/go/wasmrs/rx/mono"
)

type ns struct{}

func (n *ns) Namespace() string {
	return "nanochat.io.user.v1"
}

type UserStore interface {
	Me(ctx context.Context) mono.Mono[User]
	Load(ctx context.Context, userID uuid.UUID) mono.Mono[User]
	GetMultiple(ctx context.Context, userIds []uuid.UUID) flux.Flux[User]
	FindByHandle(ctx context.Context, handle string) mono.Mono[User]
	GetFive(ctx context.Context) flux.Flux[User]
}

// User record
type User struct {
	ns
	// User ID.
	ID uuid.UUID `json:"id" yaml:"id" msgpack:"id"`
	// Handle.
	Handle string `json:"handle" yaml:"handle" msgpack:"handle"`
}

func (u *User) Type() string {
	return "User"
}
