install:
	npm install

dev:
	npm run dev

build:
	npm run build

codegen:
  npx openapi-generator-cli generate -g typescript -i http://localhost:8080/swagger/swagger_spec -o src/generated-sources/openapi
