name: Package and Push Nanochat

on:
  push:
    branches:
      - main
      - nanochat-ci
    # paths:
    #   - "nanochat/**"

jobs:
  build-and-push-docs:
    runs-on: ubuntu-latest
    env:
      REGISTRY_USERNAME: ${{ secrets.CANDLE_REG_EXAMPLES_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.CANDLE_REG_EXAMPLES_PASSWORD }}
      BUS_PATH: "/home/runner/work/examples/examples/nanochat"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Package and push
        uses: nanobus/push-action@v1
        with:
          username: ${{ secrets.CANDLE_REG_EXAMPLES_USERNAME }}
          password: ${{ secrets.CANDLE_REG_EXAMPLES_PASSWORD }}
          path: "/home/runner/work/examples/examples/nanochat"
