name: Package and Push Nanochat

on:
  push:
    branches:
      - main
      - nanochat-ci
    # paths:
    #   - "nanochat/**"

jobs:
  build-and-push-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Package and push
        uses: nanobus/push-action@v1
        with:
          path: "nanochat"
          username: ${{ secrets.CANDLE_REG_EXAMPLES_USERNAME }}
          password: ${{ secrets.CANDLE_REG_EXAMPLES_PASSWORD }}
