name: Package and Push Nanochat

on:
  push:
    branches:
      - main
    paths:
      - "nanochat/**"
jobs:
  build-and-push-docs:
    runs-on: ubuntu-latest
    env:
      AUTH_BASEURL: https://nanochat.io/
      APP_ROOT_URL: https://nanochat.io/
      VITE_API_BASEURL: https://nanochat.io/
      API_BASEURL: https://nanochat.io/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # use nodejs action
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      # run npm build on /docs directory
      - name: Build
        run: |
          cd nanochat/ui
          npm install
          npm run build
      - name: Package and push
        uses: nanobus/push-action@v1
        with:
          path: "nanochat/bus.yaml"
          username: ${{ secrets.CANDLE_REG_EXAMPLES_USERNAME }}
          password: ${{ secrets.CANDLE_REG_EXAMPLES_PASSWORD }}
